USE pokedex;
INSERT INTO type_mul(tname, fighting, ghost) values("Normal", 2, 0);
INSERT INTO type_mul(tname, fire, water, grass, ice, ground, bug, rock, steel, fairy) values("Fire", 0.5, 2, 0.5, 0.5, 2, 0.5, 2, 0.5, 0.5);
INSERT INTO type_mul(tname, fire, water, electric, grass, ice, steel) values("Water", 0.5, 0.5, 2, 2, 0.5, 0.5);
INSERT INTO type_mul(tname, electric, ground, flying, steel) values("Electric", 0.5, 2, 0.5, 0.5);
INSERT INTO type_mul(tname, fire, water, electric, grass, ice, poison, ground, flying, bug) values("Grass", 2, 0.5, 0.5, 0.5, 2, 2, 0.5, 2, 2);
INSERT INTO type_mul(tname, fire, ice, fighting, rock, steel) values("Ice", 2, 0.5, 2, 2, 2);
INSERT INTO type_mul(tname, flying, psychic, bug, rock, dark, fairy) values("Fighting", 2, 2, 0.5, 0.5, 0.5, 2);
INSERT INTO type_mul(tname, grass, fighting, poison, ground, psychic, bug, fairy) values("Poison", 0.5, 0.5, 0.5, 2, 2, 0.5, 0.5);
INSERT INTO type_mul(tname, water, electric, grass, ice, poison, rock) values("Ground", 2, 0, 2, 2, 0.5, 0.5);
INSERT INTO type_mul(tname, electric, grass, ice, fighting, ground, bug, rock) values("Flying", 2, 0.5, 2, 0.5, 0, 0.5, 2);
INSERT INTO type_mul(tname, fighting, psychic, bug, ghost, dark) values("Psychic", 0.5, 0.5, 2, 2, 2);
INSERT INTO type_mul(tname, fire, grass, fighting, ground, flying, rock) values("Bug", 2, 0.5, 0.5, 0.5, 2, 2);
INSERT INTO type_mul(tname, normal, fire, water, grass, fighting, poison, ground, flying, steel) values("Rock", 0.5, 0.5, 2, 2, 2, 0.5, 2, 0.5, 2);
INSERT INTO type_mul(tname, normal, fighting, poison, bug, ghost, dark) values("Ghost", 0, 0, 0.5, 0.5, 2, 2);
INSERT INTO type_mul(tname, fire, water, electric, grass, ice, dragon, fairy) values("Dragon", 0.5, 0.5, 0.5, 0.5, 2, 2, 2);
INSERT INTO type_mul(tname, fighting, psychic, bug, ghost, dark, fairy) values("Dark", 2, 0, 2, 0.5, 0.5, 2);
INSERT INTO type_mul(tname, normal, fire, grass, ice, fighting, poison, ground, flying, psychic, bug, rock, dragon, steel, fairy) values("Steel", 0.5, 2, 0.5, 0.5, 2, 0, 2, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5);
INSERT INTO type_mul(tname, fighting, poison, bug, dragon, dark, steel) values("Fairy", 0.5, 2, 0.5, 0, 0.5, 2);
