USE pokedex;
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 1, 1);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 2, 2);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 3, 3);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 4, 4);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 5, 5);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 10, 6, 6);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 7, 7);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 8, 8);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 9, 9);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 10, 10);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 11, 11);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 12, 12);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 13, 13);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 14, 14);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 15, 15);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 16, 16);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 17, 17);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 18, 18);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 19, 19);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 20, 20);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 21, 21);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 22, 22);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 23, 23);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 24, 24);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 25, 25);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 26, 26);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 27, 27);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 28, 28);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 29, 29);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 30, 30);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 9, 31, 31);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 32, 32);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 33, 33);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 9, 34, 34);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 35, 35);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 36, 36);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 37, 37);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 38, 38);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 18, 39, 39);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 18, 40, 40);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 10, 41, 41);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 10, 42, 42);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 43, 43);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 44, 44);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 45, 45);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 5, 46, 46);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 5, 47, 47);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 48, 48);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 49, 49);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 50, 50);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 51, 51);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 52, 52);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 53, 53);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 54, 54);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 55, 55);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 56, 56);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 57, 57);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 58, 58);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 59, 59);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 60, 60);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 61, 61);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 7, 62, 62);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 63, 63);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 64, 64);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 65, 65);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 66, 66);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 67, 67);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 68, 68);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 69, 69);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 70, 70);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 71, 71);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 8, 72, 72);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 8, 73, 73);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 9, 74, 74);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 9, 75, 75);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 9, 76, 76);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 77, 77);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 78, 78);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 11, 79, 79);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 11, 80, 80);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 17, 81, 81);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 17, 82, 82);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 83, 83);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 84, 84);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 85, 85);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 86, 86);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 6, 87, 87);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 88, 88);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 89, 89);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 90, 90);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 6, 91, 91);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 8, 92, 92);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 8, 93, 93);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 8, 94, 94);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 9, 95, 95);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 96, 96);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 97, 97);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 98, 98);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 99, 99);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 100, 100);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 101, 101);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 11, 102, 102);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 11, 103, 103);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 104, 104);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 105, 105);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 106, 106);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 107, 107);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 108, 108);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 109, 109);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 110, 110);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 13, 111, 111);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 13, 112, 112);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 113, 113);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 114, 114);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 115, 115);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 116, 116);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 117, 117);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 118, 118);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 119, 119);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 120, 120);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 11, 121, 121);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 18, 122, 122);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 123, 123);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 11, 124, 124);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 125, 125);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 126, 126);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 127, 127);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 128, 128);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 129, 129);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 10, 130, 130);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 6, 131, 131);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 132, 132);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 133, 133);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 134, 134);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 135, 135);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 136, 136);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 137, 137);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 3, 138, 138);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 3, 139, 139);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 3, 140, 140);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 3, 141, 141);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 10, 142, 142);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 143, 143);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 10, 144, 144);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 10, 145, 145);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 10, 146, 146);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 147, 147);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 148, 148);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 10, 149, 149);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 150, 150);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 151, 151);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 152, 152);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 153, 153);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 154, 154);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 155, 155);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 156, 156);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 157, 157);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 158, 158);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 159, 159);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 160, 160);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 161, 161);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 162, 162);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 163, 163);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 164, 164);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 165, 165);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 166, 166);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 167, 167);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 168, 168);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 10, 169, 169);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 4, 170, 170);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 4, 171, 171);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 172, 172);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 173, 173);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 18, 174, 174);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 175, 175);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (18, 10, 176, 176);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 10, 177, 177);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 10, 178, 178);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 179, 179);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 180, 180);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 181, 181);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 182, 182);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 18, 183, 183);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 18, 184, 184);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 185, 185);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 186, 186);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 10, 187, 187);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 10, 188, 188);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 10, 189, 189);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 190, 190);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 191, 191);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 192, 192);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 193, 193);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 194, 194);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 195, 195);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 196, 196);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 197, 197);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 10, 198, 198);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 11, 199, 199);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 200, 200);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 201, 201);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 202, 202);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 11, 203, 203);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 204, 204);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 17, 205, 205);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 206, 206);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 10, 207, 207);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 9, 208, 208);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 209, 209);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 210, 210);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 8, 211, 211);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 17, 212, 212);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 13, 213, 213);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 7, 214, 214);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 6, 215, 215);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 216, 216);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 217, 217);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 218, 218);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 13, 219, 219);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 9, 220, 220);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 9, 221, 221);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 13, 222, 222);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 223, 223);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 224, 224);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 10, 225, 225);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 10, 226, 226);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 10, 227, 227);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 2, 228, 228);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 2, 229, 229);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 15, 230, 230);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 231, 231);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 232, 232);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 233, 233);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 234, 234);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 235, 235);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 236, 236);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 237, 237);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 11, 238, 238);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 239, 239);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 240, 240);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 241, 241);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 242, 242);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 243, 243);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 244, 244);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 245, 245);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 9, 246, 246);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 9, 247, 247);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 16, 248, 248);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 10, 249, 249);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 10, 250, 250);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 5, 251, 251);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 252, 252);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 253, 253);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 254, 254);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 255, 255);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 7, 256, 256);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 7, 257, 257);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 258, 258);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 259, 259);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 260, 260);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 261, 261);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 262, 262);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 263, 263);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 264, 264);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 265, 265);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 266, 266);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 267, 267);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 268, 268);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 269, 269);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 5, 270, 270);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 5, 271, 271);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 5, 272, 272);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 273, 273);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 16, 274, 274);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 16, 275, 275);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 276, 276);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 277, 277);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 10, 278, 278);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 10, 279, 279);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 18, 280, 280);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 18, 281, 281);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 18, 282, 282);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 3, 283, 283);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 284, 284);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 285, 285);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 7, 286, 286);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 287, 287);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 288, 288);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 289, 289);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 9, 290, 290);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 291, 291);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 14, 292, 292);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 293, 293);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 294, 294);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 295, 295);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 296, 296);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 297, 297);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 18, 298, 298);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 299, 299);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 300, 300);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 301, 301);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 14, 302, 302);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 18, 303, 303);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 13, 304, 304);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 13, 305, 305);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 13, 306, 306);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (7, 11, 307, 307);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (7, 11, 308, 308);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 309, 309);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 310, 310);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 311, 311);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 312, 312);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 313, 313);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 314, 314);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 315, 315);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 316, 316);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 317, 317);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 16, 318, 318);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 16, 319, 319);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 320, 320);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 321, 321);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 9, 322, 322);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 9, 323, 323);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 324, 324);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 325, 325);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 326, 326);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 327, 327);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 328, 328);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 15, 329, 329);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 15, 330, 330);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 331, 331);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 16, 332, 332);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 333, 333);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 10, 334, 334);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 335, 335);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 336, 336);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 11, 337, 337);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 11, 338, 338);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 339, 339);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 340, 340);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 341, 341);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 16, 342, 342);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 11, 343, 343);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 11, 344, 344);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 5, 345, 345);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 5, 346, 346);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 12, 347, 347);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 12, 348, 348);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 349, 349);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 350, 350);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 351, 351);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 352, 352);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 353, 353);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 354, 354);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 355, 355);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 356, 356);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 10, 357, 357);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 358, 358);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 359, 359);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 360, 360);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 361, 361);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 362, 362);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 3, 363, 363);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 3, 364, 364);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 3, 365, 365);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 366, 366);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 367, 367);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 368, 368);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 13, 369, 369);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 370, 370);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 371, 371);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 372, 372);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 10, 373, 373);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 11, 374, 374);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 11, 375, 375);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 11, 376, 376);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 377, 377);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 378, 378);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (17, 379, 379);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 11, 380, 380);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 11, 381, 381);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 382, 382);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 383, 383);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 10, 384, 384);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 11, 385, 385);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 386, 386);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 387, 387);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 388, 388);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 9, 389, 389);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 390, 390);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 7, 391, 391);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 7, 392, 392);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 393, 393);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 394, 394);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 17, 395, 395);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 396, 396);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 397, 397);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 398, 398);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 399, 399);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 3, 400, 400);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 401, 401);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 402, 402);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 403, 403);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 404, 404);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 405, 405);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 406, 406);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 407, 407);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 408, 408);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 409, 409);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 17, 410, 410);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 17, 411, 411);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 412, 412);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 5, 413, 413);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 414, 414);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 415, 415);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 416, 416);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 417, 417);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 418, 418);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 419, 419);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 420, 420);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 421, 421);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 422, 422);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 423, 423);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 424, 424);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 10, 425, 425);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 10, 426, 426);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 427, 427);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 428, 428);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 429, 429);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 10, 430, 430);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 431, 431);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 432, 432);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 433, 433);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 16, 434, 434);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 16, 435, 435);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 11, 436, 436);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 11, 437, 437);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 438, 438);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 18, 439, 439);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 440, 440);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 441, 441);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 16, 442, 442);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 9, 443, 443);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 9, 444, 444);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 9, 445, 445);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 446, 446);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 447, 447);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (7, 17, 448, 448);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 449, 449);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 450, 450);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 12, 451, 451);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 16, 452, 452);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 7, 453, 453);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 7, 454, 454);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 455, 455);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 456, 456);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 457, 457);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 10, 458, 458);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 6, 459, 459);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 6, 460, 460);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 6, 461, 461);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 17, 462, 462);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 463, 463);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 13, 464, 464);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 465, 465);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 466, 466);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 467, 467);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (18, 10, 468, 468);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 469, 469);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 470, 470);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 471, 471);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 10, 472, 472);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 9, 473, 473);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 474, 474);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 7, 475, 475);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 17, 476, 476);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 477, 477);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (6, 14, 478, 478);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 14, 479, 479);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 480, 480);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 481, 481);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 482, 482);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 15, 483, 483);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 15, 484, 484);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 17, 485, 485);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 486, 486);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 15, 487, 487);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 488, 488);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 489, 489);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 490, 490);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 491, 491);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 492, 492);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 493, 493);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 2, 494, 494);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 495, 495);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 496, 496);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 497, 497);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 498, 498);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 7, 499, 499);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 7, 500, 500);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 501, 501);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 502, 502);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 503, 503);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 504, 504);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 505, 505);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 506, 506);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 507, 507);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 508, 508);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 509, 509);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 510, 510);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 511, 511);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 512, 512);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 513, 513);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 514, 514);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 515, 515);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 516, 516);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 517, 517);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 518, 518);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 519, 519);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 520, 520);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 521, 521);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 522, 522);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 523, 523);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 524, 524);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 525, 525);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 526, 526);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 10, 527, 527);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 10, 528, 528);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 529, 529);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 17, 530, 530);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 531, 531);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 532, 532);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 533, 533);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 534, 534);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 535, 535);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 536, 536);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 9, 537, 537);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 538, 538);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 539, 539);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 5, 540, 540);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 5, 541, 541);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 5, 542, 542);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 543, 543);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 544, 544);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 8, 545, 545);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 18, 546, 546);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 18, 547, 547);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 548, 548);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 549, 549);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 550, 550);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 16, 551, 551);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 16, 552, 552);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 16, 553, 553);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 554, 554);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 555, 555);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 556, 556);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 13, 557, 557);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 13, 558, 558);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 7, 559, 559);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 7, 560, 560);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 10, 561, 561);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 562, 562);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (14, 563, 563);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 13, 564, 564);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 13, 565, 565);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 10, 566, 566);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 10, 567, 567);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 568, 568);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 569, 569);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 570, 570);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (16, 571, 571);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 572, 572);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 573, 573);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 574, 574);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 575, 575);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 576, 576);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 577, 577);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 578, 578);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 579, 579);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 10, 580, 580);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 10, 581, 581);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 582, 582);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 583, 583);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 584, 584);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 5, 585, 585);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 5, 586, 586);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 10, 587, 587);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 588, 588);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 17, 589, 589);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 590, 590);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 8, 591, 591);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 14, 592, 592);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 14, 593, 593);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 594, 594);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 4, 595, 595);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 4, 596, 596);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 17, 597, 597);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 17, 598, 598);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (17, 599, 599);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (17, 600, 600);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (17, 601, 601);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 602, 602);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 603, 603);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 604, 604);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 605, 605);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 606, 606);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 2, 607, 607);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 2, 608, 608);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 2, 609, 609);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 610, 610);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 611, 611);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 612, 612);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 613, 613);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 614, 614);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 615, 615);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 616, 616);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 617, 617);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 4, 618, 618);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 619, 619);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 620, 620);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 621, 621);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 14, 622, 622);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 14, 623, 623);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 17, 624, 624);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 17, 625, 625);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 626, 626);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 627, 627);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 628, 628);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 10, 629, 629);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 10, 630, 630);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 631, 631);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 17, 632, 632);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 15, 633, 633);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 15, 634, 634);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 15, 635, 635);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 2, 636, 636);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 2, 637, 637);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 7, 638, 638);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 7, 639, 639);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 7, 640, 640);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (10, 641, 641);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 10, 642, 642);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 2, 643, 643);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 4, 644, 644);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (9, 10, 645, 645);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 6, 646, 646);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 7, 647, 647);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 11, 648, 648);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 17, 649, 649);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 650, 650);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 651, 651);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 7, 652, 652);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 653, 653);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 654, 654);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 11, 655, 655);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 656, 656);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 657, 657);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 16, 658, 658);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 659, 659);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 9, 660, 660);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 661, 661);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 10, 662, 662);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 10, 663, 663);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 664, 664);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 665, 665);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 10, 666, 666);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 1, 667, 667);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 1, 668, 668);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 669, 669);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 670, 670);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 671, 671);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 672, 672);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 673, 673);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 674, 674);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (7, 16, 675, 675);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 676, 676);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 677, 677);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 678, 678);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 14, 679, 679);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 14, 680, 680);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 14, 681, 681);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 682, 682);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 683, 683);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 684, 684);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 685, 685);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 11, 686, 686);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 11, 687, 687);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 3, 688, 688);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 3, 689, 689);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 3, 690, 690);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 15, 691, 691);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 692, 692);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 693, 693);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 1, 694, 694);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 1, 695, 695);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 15, 696, 696);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 15, 697, 697);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 6, 698, 698);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 6, 699, 699);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 700, 700);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (7, 10, 701, 701);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 18, 702, 702);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 18, 703, 703);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 704, 704);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 705, 705);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 706, 706);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 18, 707, 707);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 5, 708, 708);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 5, 709, 709);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 5, 710, 710);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 5, 711, 711);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 712, 712);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (6, 713, 713);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (10, 15, 714, 714);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (10, 15, 715, 715);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 716, 716);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 10, 717, 717);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 9, 718, 718);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 18, 719, 719);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 14, 720, 720);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 3, 721, 721);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 10, 722, 722);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 10, 723, 723);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 14, 724, 724);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 725, 725);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (2, 726, 726);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 16, 727, 727);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 728, 728);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 729, 729);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 18, 730, 730);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 731, 731);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 732, 732);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 10, 733, 733);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 734, 734);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 735, 735);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (12, 736, 736);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 4, 737, 737);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 4, 738, 738);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 739, 739);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (7, 6, 740, 740);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 10, 741, 741);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 18, 742, 742);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 18, 743, 743);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 744, 744);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (13, 745, 745);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 746, 746);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 3, 747, 747);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 3, 748, 748);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 749, 749);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (9, 750, 750);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 12, 751, 751);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 12, 752, 752);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 753, 753);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 754, 754);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 18, 755, 755);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 18, 756, 756);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 2, 757, 757);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 2, 758, 758);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 7, 759, 759);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 7, 760, 760);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 761, 761);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 762, 762);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (5, 763, 763);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (18, 764, 764);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 11, 765, 765);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (7, 766, 766);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 3, 767, 767);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 3, 768, 768);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 9, 769, 769);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 9, 770, 770);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (3, 771, 771);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 772, 772);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 773, 773);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 10, 774, 774);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (1, 775, 775);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 15, 776, 776);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 17, 777, 777);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 18, 778, 778);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 11, 779, 779);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (1, 15, 780, 780);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (14, 5, 781, 781);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (15, 782, 782);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 7, 783, 783);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (15, 7, 784, 784);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (4, 18, 785, 785);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 18, 786, 786);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 18, 787, 787);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (3, 18, 788, 788);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 789, 789);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 790, 790);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 17, 791, 791);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (11, 14, 792, 792);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 8, 793, 793);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 7, 794, 794);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (12, 7, 795, 795);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 796, 796);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 10, 797, 797);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (5, 17, 798, 798);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (16, 15, 799, 799);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (11, 800, 800);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (17, 18, 801, 801);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (7, 14, 802, 802);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (8, 803, 803);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (8, 15, 804, 804);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (13, 17, 805, 805);
INSERT INTO pokemon (primary_type_id, secondary_type_id, base_stats_id, name_id) values (2, 14, 806, 806);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (4, 807, 807);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (17, 808, 808);
INSERT INTO pokemon (primary_type_id, base_stats_id, name_id) values (17, 809, 809);
